#!/bin/bash
mkdir -p arrow-21.0.0/build
pushd arrow-21.0.0
pushd build


cmake -G "Visual Studio 17 2022" \
  -DCMAKE_BUILD_TYPE=Debug \
  -DARROW_BUILD_SHARED=OFF \
  -DARROW_BUILD_STATIC=ON \
  -DARROW_PARQUET=ON \
  -DARROW_BUILD_TESTS=OFF \
  -DARROW_BUILD_BENCHMARKS=OFF \
  -DARROW_BUILD_EXAMPLES=OFF \
  -DARROW_BUILD_UTILITIES=OFF \
  -DARROW_CSV=OFF \
  -DARROW_DATASET=OFF \
  -DARROW_FILESYSTEM=OFF \
  -DARROW_FLIGHT=OFF \
  -DARROW_GANDIVA=OFF \
  -DARROW_HDFS=OFF \
  -DARROW_JSON=OFF \
  -DARROW_ORC=OFF \
  -DARROW_PLASMA=OFF \
  -DARROW_PYTHON=OFF \
  -DARROW_S3=OFF \
  -DARROW_WITH_BROTLI=OFF \
  -DARROW_WITH_BZ2=OFF \
  -DARROW_WITH_LZ4=OFF \
  -DARROW_WITH_SNAPPY=OFF \
  -DARROW_WITH_ZLIB=OFF \
  -DARROW_WITH_ZSTD=OFF \
  -DARROW_COMPUTE=OFF \
  -DARROW_IPC=OFF \
  -DARROW_JEMALLOC=OFF \
  -DARROW_MIMALLOC=OFF \
  -DARROW_DEPENDENCY_SOURCE=BUNDLED \
  -DARROW_DEPENDENCY_USE_SHARED=OFF \
  -DPARQUET_BUILD_EXECUTABLES=OFF \
  -DPARQUET_BUILD_EXAMPLES=OFF \
  ../cpp --fresh

cmake --build . --parallel 4 --config Debug --target arrow_static parquet_static

popd
popd
pwd